# Generated by Django 5.0.6 on 2024-05-13 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlumberTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('task_type', models.CharField(choices=[('connection', 'connection'), ('problem', 'problem')], max_length=100)),
                ('description', models.TextField()),
                ('registration_number', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('photo_ID', models.ImageField(upload_to='photo_id/')),
                ('location', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('waiting', 'waiting'), ('inprogress', 'inprogress'), ('started', 'started'), ('completed', 'completed')], max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Internet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_modem', models.ImageField(upload_to='internet/')),
                ('modem_SN', models.CharField(max_length=100)),
                ('optical_cable', models.CharField(max_length=100)),
                ('fastconnector', models.CharField(max_length=100)),
                ('siqnal', models.CharField(max_length=100)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internet', to='services.task')),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_modem', models.ImageField(upload_to='tv/')),
                ('modem_SN', models.CharField(max_length=100)),
                ('rg6_cable', models.CharField(max_length=100)),
                ('f_connector', models.CharField(max_length=100)),
                ('splitter', models.CharField(max_length=100)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tv', to='services.task')),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_modem', models.ImageField(upload_to='voice/')),
                ('modem_SN', models.CharField(max_length=100)),
                ('home_number', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='services.task')),
            ],
        ),
    ]
