# Generated by Django 5.0.6 on 2024-05-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'waiting'), ('inprogress', 'inprogress'), ('started', 'started'), ('completed', 'completed')], default='waiting', max_length=100, null=True),
        ),
    ]
