# Generated by Django 5.0.6 on 2024-05-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('inprogress', 'inprogress'), ('started', 'started'), ('completed', 'completed')], default='waiting', max_length=100),
        ),
    ]
