# Generated by Django 5.0.4 on 2024-05-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_task_is_internet_task_is_tv_task_is_voice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plumbertask',
            name='equipment_az',
        ),
        migrations.RemoveField(
            model_name='plumbertask',
            name='equipment_en',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='task',
            name='location_az',
        ),
        migrations.RemoveField(
            model_name='task',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='task',
            name='note_az',
        ),
        migrations.RemoveField(
            model_name='task',
            name='note_en',
        ),
    ]
