# Generated by Django 5.0.6 on 2024-05-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='location_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='location_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='note_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='note_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status_az',
            field=models.CharField(choices=[('waiting', 'waiting'), ('inprogress', 'inprogress'), ('started', 'started'), ('completed', 'completed')], default='waiting', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status_en',
            field=models.CharField(choices=[('waiting', 'waiting'), ('inprogress', 'inprogress'), ('started', 'started'), ('completed', 'completed')], default='waiting', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type_az',
            field=models.CharField(choices=[('connection', 'connection'), ('problem', 'problem')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type_en',
            field=models.CharField(choices=[('connection', 'connection'), ('problem', 'problem')], max_length=100, null=True),
        ),
    ]
