# Generated by Django 5.0.4 on 2024-05-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_meeting_participants'),
        ('services', '0003_remove_plumbertask_equipment_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='photo_ID',
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ManyToManyField(related_name='group_tasks', to='accounts.group'),
        ),
    ]
