# Generated by Django 5.0.4 on 2024-05-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_meeting_participants'),
        ('services', '0004_remove_task_photo_id_task_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='group_tasks', to='accounts.group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
