# Generated by Django 5.0.6 on 2024-05-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_task_task_type_az_remove_task_task_type_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(max_length=100),
        ),
    ]
