# Generated by Django 5.0.6 on 2024-05-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_task_task_type_alter_task_task_type_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connection', 'connection'), ('problem', 'problem')], max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type_az',
            field=models.CharField(choices=[('connection', 'connection'), ('problem', 'problem')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type_en',
            field=models.CharField(choices=[('connection', 'connection'), ('problem', 'problem')], max_length=100, null=True),
        ),
    ]
