# Generated by Django 5.0.6 on 2024-05-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_task_task_type_alter_task_task_type_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type_az',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type_en',
        ),
    ]
