# Generated by Django 5.0.6 on 2024-05-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_task_task_type_az_task_task_type_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type_az',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type_en',
        ),
    ]
