# Generated by Django 5.0.6 on 2024-05-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_task_task_type_az_remove_task_task_type_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plumbertask',
            old_name='brand',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='plumbertask',
            name='model',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status_az',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status_en',
        ),
        migrations.AddField(
            model_name='plumbertask',
            name='equipment_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plumbertask',
            name='equipment_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
