# Generated by Django 5.0.4 on 2024-05-18 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('meeting_type', models.CharField(choices=[('Şənlik', 'Şənlik'), ('Toplantı', 'Toplantı'), ('Konfrans', 'Konfrans'), ('Seminar', 'Seminar')], max_length=100)),
                ('date', models.DateTimeField()),
                ('meeting_description', models.TextField(blank=True, null=True)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
