# version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: "always"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../nginx.conf:/etc/nginx/nginx.conf
      - ../../static:/app/static
      - ../../media:/app/media
    depends_on:
      - "app"

  letsencrypt-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=aytacmehdizade08@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy

  app:
    container_name: app
    build: ../..
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=78.47.82.5
      - VIRTUAL_PORT=8000
      - HTTP_PORT=8000
      - STATS_PORT=8001
    volumes:
      - ../..:/code
    ports:
      - "8015:8000"
    links:
      - postgres
    depends_on:
      - "postgres"

  postgres:
    container_name: postgres-db
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env

  redis:
    build:
      context: .
      dockerfile: redis.dockerfile
    image: redis:4.0.11
    restart: "on-failure"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redisdb:/var/lib/redis
    env_file: .env

volumes:
  letsencrypt-certs:
  letsencrypt-vhost-d:
  letsencrypt-html:

networks:
  default:
    external: True
    name: nginx-proxy
